# Generated by Django 5.1.2 on 2024-11-29 12:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='batch',
            fields=[
                ('id', models.IntegerField(default=None, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='standardCurves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curveName', models.CharField()),
                ('stage1', models.FloatField(blank=True, null=True)),
                ('stage2', models.FloatField(blank=True, null=True)),
                ('stage3', models.FloatField(blank=True, null=True)),
                ('stage4', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sampleSoil',
            fields=[
                ('id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('batch_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='soilcalc.batch')),
                ('user_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='element',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('value', models.FloatField(blank=True, null=True)),
                ('sampleSoil_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='soilcalc.samplesoil')),
            ],
        ),
    ]
