# Generated by Django 5.1.2 on 2024-11-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soilcalc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplesoil',
            name='al',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='samplesoil',
            name='ca',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='samplesoil',
            name='clay',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='samplesoil',
            name='claySilt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='samplesoil',
            name='cu',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='samplesoil',
            name='emptyBecker1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='samplesoil',
            name='emptyBecker2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='samplesoil',
            name='fe',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='samplesoil',
            name='hAl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='samplesoil',
            name='mg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='samplesoil',
            name='mn',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='samplesoil',
            name='na',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='samplesoil',
            name='organicMaterial',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='samplesoil',
            name='pRem',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='samplesoil',
            name='ph',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='samplesoil',
            name='phosporo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='samplesoil',
            name='potassium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='samplesoil',
            name='sample',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='samplesoil',
            name='zn',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
