# Generated by Django 5.1.2 on 2024-11-29 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soilcalc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standardcurves',
            old_name='stage1',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='standardcurves',
            name='curveName',
        ),
        migrations.RemoveField(
            model_name='standardcurves',
            name='id',
        ),
        migrations.RemoveField(
            model_name='standardcurves',
            name='stage2',
        ),
        migrations.RemoveField(
            model_name='standardcurves',
            name='stage3',
        ),
        migrations.RemoveField(
            model_name='standardcurves',
            name='stage4',
        ),
        migrations.AddField(
            model_name='standardcurves',
            name='bath_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='soilcalc.batch'),
        ),
        migrations.AddField(
            model_name='standardcurves',
            name='curve_element',
            field=models.CharField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='element',
            name='sampleSoil_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='soilcalc.samplesoil'),
        ),
    ]
