# Generated by Django 5.1.2 on 2024-11-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soilcalc', '0002_alter_samplesoil_al_alter_samplesoil_ca_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='standardCurves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curveName', models.CharField()),
                ('stage1', models.FloatField(blank=True, null=True)),
                ('stage2', models.FloatField(blank=True, null=True)),
                ('stage3', models.FloatField(blank=True, null=True)),
                ('stage4', models.FloatField(blank=True, null=True)),
                ('stage5', models.FloatField(blank=True, null=True)),
                ('stage6', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
