# Generated by Django 5.1.2 on 2024-11-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soilcalc', '0003_standardcurves'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplesoil',
            name='id',
        ),
        migrations.AlterField(
            model_name='samplesoil',
            name='sample',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
