# Generated by Django 5.1.2 on 2025-06-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionsample',
            name='agua_fisico_quimica',
            field=models.BooleanField(default=True, verbose_name='Água - Físico-Química'),
        ),
        migrations.AddField(
            model_name='submissionsample',
            name='agua_microbiologico',
            field=models.BooleanField(default=False, verbose_name='Água - Microbiológico'),
        ),
        migrations.AddField(
            model_name='submissionsample',
            name='solo_fertilidade_basica',
            field=models.BooleanField(default=False, verbose_name='Solo - Fertilidade Básica'),
        ),
        migrations.AddField(
            model_name='submissionsample',
            name='solo_fertilidade_completa',
            field=models.BooleanField(default=False, verbose_name='Solo - Fertilidade Completa'),
        ),
        migrations.AddField(
            model_name='submissionsample',
            name='tecido_vegetal',
            field=models.BooleanField(default=False, verbose_name='Tecido Vegetal'),
        ),
    ]
