# Generated by Django 5.1.2 on 2025-06-10 20:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_submissionsample_agua_fisico_quimica_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissionsample',
            name='user_id',
        ),
        migrations.AddField(
            model_name='submissionsample',
            name='num_agua_fisico_quimica',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Qtde amostras'),
        ),
        migrations.AddField(
            model_name='submissionsample',
            name='num_agua_microbiologico',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='submissionsample',
            name='num_solo_fertilidade_basica',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='submissionsample',
            name='num_solo_fertilidade_completa',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='submissionsample',
            name='num_tecido_vegetal',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='submissionsample',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submissionsample',
            name='agua_fisico_quimica',
            field=models.BooleanField(default=False, verbose_name='Água – Físico-Química'),
        ),
        migrations.AlterField(
            model_name='submissionsample',
            name='agua_microbiologico',
            field=models.BooleanField(default=False, verbose_name='Água – Microbiológico'),
        ),
        migrations.AlterField(
            model_name='submissionsample',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='submissionsample',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='submissionsample',
            name='solo_fertilidade_basica',
            field=models.BooleanField(default=False, verbose_name='Solo – Fertilidade Básica'),
        ),
        migrations.AlterField(
            model_name='submissionsample',
            name='solo_fertilidade_completa',
            field=models.BooleanField(default=False, verbose_name='Solo – Fertilidade Completa'),
        ),
    ]
