# Generated by Django 5.1.2 on 2025-08-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_remove_submissionsample_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionsample',
            name='status',
            field=models.BooleanField(default=False, verbose_name='status'),
        ),
    ]
