# Generated by Django 5.1.2 on 2025-08-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_submissionsample_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionsample',
            name='status',
            field=models.BooleanField(default=None, null=True, verbose_name='status'),
        ),
    ]
